fix bug that the last line of input file is ignored
trailofbits/onesixtyone pull request #14
Opened 2018-11-23 09:42 UTC by adamhj

Hello, I found a bug in this tool that when it runs with `-i inputfile` parameter, the last line of the inputfile is ignored (if the file is not end with an empty new line), so this patch's main purpose is to fix this.
On the other hand, there is a line of enforced `host_count = 1;` when parsing target host in the command line, which override host_count set in `add_host()`, this disables netmask style target in command line, which feels pointless, so I just comment it out to allow target with netmask in command line args.

2018-11-23 09:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/trailofbits/onesixtyone?pullRequest=14) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/trailofbits/onesixtyone?pullRequest=14) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/trailofbits/onesixtyone?pullRequest=14) it.</sub>

2018-11-23 20:11 UTC, disconnect3d commented on onesixtyone.c
> +      if (ch != '\r')
Can we make just:
```c
else if (ch != '\r') {
    buf[c++] = ch;
}
```

2018-11-23 20:22 UTC, disconnect3d commented on onesixtyone.c
> +  while (1) {
Let's change it to a `do { ... } while (ch != EOF);`, as it is better to inform the future readers of the code that it is not an infinite loop.

Also a fun-fact in C [an infinite loop with a constant expression as condition is valid and well-defined](https://stackoverflow.com/questions/16436237/is-while1-undefined-behavior-in-c) but in C++ [it is an undefined behavior](https://stackoverflow.com/questions/3592557/optimizing-away-a-while1-in-c0x/).

2018-11-23 20:26 UTC, disconnect3d requested changes

2018-11-23 20:26 UTC, disconnect3d commented on onesixtyone.c
> +#define MAX_HOSTS 16777215
What is the reason for this change?

2018-11-23 20:26 UTC, disconnect3d commented on onesixtyone.c
> +  char buf[65535];
Why do we need such big buffer? I am not sure if it is that safe to allocate so much memory on the stack too.

2018-11-23 20:26 UTC, disconnect3d commented on onesixtyone.c
> +    // host_count = 1;
Pushing a commented out line is rarely a good thing. As a new programmer reading this I might ask: why is this comment here? What will happen if I uncomment it? What are the consequences? etc.

Let me think more about this change and/or ask someone else about it as I am not sure if we want to address your concern:
> On the other hand, there is a line of enforced host_count = 1; when parsing target host in the command line, which override host_count set in add_host(), this disables netmask style target in command line, which feels pointless, so I just comment it out to allow target with netmask in command line args.

by removing this line.

2018-11-24 07:55 UTC, adamhj commented on onesixtyone.c
> +      if (ch != '\r')
Yes, I didn't notice this

2018-11-24 08:00 UTC, adamhj commented on onesixtyone.c
> +#define MAX_HOSTS 16777215
Ah, this is because my use case may require more than 65535 hosts so I change this in my repository. You may revert it.

2018-11-24 08:07 UTC, adamhj commented on onesixtyone.c
> +  char buf[65535];
The original logic allows space/tab as IP/mask splitter in the input file
`if (ch == '\n' || ch == ' ' || ch == '\t')`
So I think the 100 chars limit for a line is too small for this.
Or should we just reject multiple IP/mask in one line?

2018-11-25 00:55 UTC, disconnect3d commented on onesixtyone.c
> +        buf[c++] = ch;
```suggestion
      buf[c++] = ch;
```
It seems the rest of the code uses 2-spaces indents.

2018-12-12 20:21 UTC, disconnect3d commented on onesixtyone.c
> +    // host_count = 1;
Does everything works as expected without this line (I assume we remove it bcoz of some cli argument, what if we don't pass that cli arg?)? If so, lets remove it.

2019-02-14 16:08 UTC, merged